// Writes src/helper-jar.js from build/acm-helper.jar (called by build.sh).
const fs = require("fs"), crypto = require("crypto"), path = require("path");
const b = fs.readFileSync(path.join(__dirname, "build", "acm-helper.jar"));
const h = crypto.createHash("sha256").update(b).digest("hex").slice(0, 12);
fs.writeFileSync(path.join(__dirname, "..", "src", "helper-jar.js"),
  `// Generated by helper/build.sh. Do not edit.\nexport const HELPER_JAR_B64 = "${b.toString("base64")}";\nexport const HELPER_JAR_HASH = "${h}";\n`);
console.log("helper jar", b.length, "bytes, hash", h);
